#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["fonttools>=4.60", "brotli>=1.1"]
# ///
"""Generate the Lab271 wordmark and badge SVGs.

Both marks set text in Inter, the brand kit's open stand-in for TT Interphases.
Rather than relying on Inter being installed wherever the SVG is rendered, this
outlines the glyphs to paths, which is what labs-branding's logo/README.md asks
for before an SVG ships.

Run via `mise run docs-marks`, then `mise run docs-icons` to re-export the
favicon PNGs from the new badge.

Palette and lockup rules: labs-branding, brand/visual-identity.md sections 1-3.
"""

from __future__ import annotations

import urllib.request
from pathlib import Path

from fontTools.misc.transform import Transform
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

# Inter, latin subset, one file per weight. Pinned to a major version so the
# outlines don't shift under us without a deliberate bump.
FONT_URLS = {
    600: "https://cdn.jsdelivr.net/npm/@fontsource/inter@5/files/inter-latin-600-normal.woff2",
    700: "https://cdn.jsdelivr.net/npm/@fontsource/inter@5/files/inter-latin-700-normal.woff2",
}

NAVY = "#1A1F36"
BLUE = "#6C8EEF"
BLUE_LIGHT = "#A8C0FF"
TEAL = "#36C5B0"
WHITE = "#FFFFFF"

HERE = Path(__file__).resolve().parent
ASSETS = HERE.parent / "src" / "assets"
CACHE = HERE / ".font-cache"


def font(weight: int) -> TTFont:
    CACHE.mkdir(exist_ok=True)
    path = CACHE / f"inter-{weight}.woff2"
    if not path.exists():
        print(f"downloading {FONT_URLS[weight]}")
        with urllib.request.urlopen(FONT_URLS[weight]) as response:
            path.write_bytes(response.read())
    return TTFont(path)


def run(weight: int, text: str, size: float, tracking: float = 0.0, x: float = 0.0, y: float = 0.0):
    """Outline `text` at `size`, returning (path data, advance width, ink bounds).

    `y` is the baseline; `tracking` is extra space per glyph, in the same units
    as `size`. No shaping or kerning: the marks are short and set with explicit
    tracking anyway.
    """
    face = font(weight)
    scale = size / face["head"].unitsPerEm
    cmap = face.getBestCmap()
    glyphs = face.getGlyphSet()
    widths = face["hmtx"]

    pen_x = x
    paths = []
    bounds = BoundsPen(glyphs)
    for char in text:
        name = cmap[ord(char)]
        placement = Transform(scale, 0, 0, -scale, pen_x, y)
        svg = SVGPathPen(glyphs, ntos=lambda value: f"{value:.2f}")
        glyphs[name].draw(TransformPen(svg, placement))
        if svg.getCommands():
            paths.append(svg.getCommands())
        glyphs[name].draw(TransformPen(bounds, placement))
        pen_x += widths[name][0] * scale + tracking
    # the trailing tracking is space after the last glyph, not part of the run
    return " ".join(paths), pen_x - x - tracking, bounds.bounds


def wordmark() -> str:
    """Horizontal lockup: white "Lab", blue-light "271", tight tracking."""
    size, tracking, baseline = 56, -1.1, 100.0
    lab, lab_width, lab_bounds = run(700, "Lab", size, tracking, 0, baseline)
    num, _, num_bounds = run(700, "271", size, tracking, lab_width + tracking, baseline)

    x0 = min(lab_bounds[0], num_bounds[0])
    y0 = min(lab_bounds[1], num_bounds[1])
    x1 = max(lab_bounds[2], num_bounds[2])
    y1 = max(lab_bounds[3], num_bounds[3])

    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="{x0:.2f} {y0:.2f} {x1 - x0:.2f} {y1 - y0:.2f}"
     role="img" aria-label="Lab271">
  <!-- Lab271 wordmark, sentence case, Inter Bold outlined to paths. Generated by
       scripts/refresh-marks.py; edit that, not these paths. Sits on the navy nav
       bar in both color modes, so the fills are fixed. -->
  <path fill="{WHITE}" d="{lab}"/>
  <path fill="{BLUE_LIGHT}" d="{num}"/>
</svg>
"""


def badge() -> str:
    """Concept A, "the door plate": tracked "Lab" over a large "271", teal rule."""
    side, radius = 512, 117  # radius keeps concept A's 32-at-140px proportion
    _, lab_width, _ = run(600, "Lab", 80, 14.6)
    _, num_width, _ = run(700, "271", 212, -4)
    # centre both lines, ignoring the trailing tracking on "Lab"
    lab, _, _ = run(600, "Lab", 80, 14.6, (side - lab_width) / 2, 168)
    num, _, _ = run(700, "271", 212, -4, (side - num_width) / 2, 372)

    rule_width, rule_height = 190, 22
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {side} {side}"
     role="img" aria-label="Lab271">
  <!-- Lab271 badge: concept A, the door plate at Boeing Avenue 271. Generated by
       scripts/refresh-marks.py; edit that, not these paths. Master for the
       favicon PNGs, re-export those with scripts/refresh-icons.sh. The teal rule
       is this composition's one spark. -->
  <rect width="{side}" height="{side}" rx="{radius}" fill="{NAVY}"/>
  <path fill="{BLUE}" d="{lab}"/>
  <path fill="{WHITE}" d="{num}"/>
  <rect x="{(side - rule_width) / 2:.0f}" y="410" width="{rule_width}" height="{rule_height}" rx="{rule_height / 2}" fill="{TEAL}"/>
</svg>
"""


for name, svg in (("logo.svg", wordmark()), ("badge.svg", badge())):
    (ASSETS / name).write_text(svg)
    print(f"wrote {ASSETS / name}")
